name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: registry.gama-kltn-fe.online
        username: ${{ secrets.DOCKER_USERNAME }}  # Sử dụng GitHub username từ secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker registry password từ secrets

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  # Chỉ định Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_REGISTRY_HOST }}/meow-app/${{ github.repository }}:${{ github.sha }}  # Sử dụng SHA1 của commit làm tag

    - name: Logout from Docker Registry
      run: docker logout ${{ secrets.DOCKER_REGISTRY_HOST }}
